### PR TITLE
Start implementing multi-index support (WIP)

### PR DESCRIPTION
**Pull request by mvantellingen**
For now we simply create distinct repositories without any inheritance (See #108)

TODO: 
 - [x] Per repository credentials
 - [x] Backwards compatibility for urls (should point to default repo)
 - [x] Add team structure
 - [x] Interface to manage members within teams
 - [x] Interface to manage repositories
 - [x] Add user credentials / keys
 - [x] Impement new permission model
 - [x] Add proper layout/frontend code for all new pages
 - [x] Update unittests
 - [x] Remove django-userena
 - [x] Basic python 3 support (should be done in an other branch, but bla)
 - [x] Bootstrap 3 :smile: 
 - [ ] Update changelog / documentation

### CODE REVIEW

**Comment by mvantellingen** [comment]
@canassa perhaps we want to get a 1.0 released before this is merged in the develop branch.

**Comment by mvantellingen** [comment]
And I'll probably squash and re-order various commits in this branch

**Comment by canassa** [comment]
@mvantellingen PR looking great so far :+1:  What do you have in mind for a 1.0 release?

**Comment by mvantellingen** [comment]
@canassa Thanks. This PR is getting a bit out of hand :smile: 

I thought about getting the current release tagged as 1.0. But I think this is shaping up nicely, so perhaps we should wait. It is now somewhat feature complete (except the permission checks), but I need to add tests and fix some styling issues.

**Pull request merged**
