### PR TITLE
Simplify test requirements and explain manual py.test usage

### PR DESCRIPTION
**Pull request by asfaltboy**

### CODE REVIEW

**Comment by mvantellingen** [comment]
Hi,

Thanks for the PR.  This used to be the case, although I've changed this in a imho better way via the `extras_requires` in #154

**Comment by mvantellingen** [comment]
I will merge the doc updates, which are excellent, thanks :-)

**Comment by asfaltboy** [comment]
Thanks! If you prefer, I can rework it into your branch

**Comment by mvantellingen** [comment]
@asfaltboy Cool! I've just merged the multi-index branch, if you could rebase this PR on develop then that would be great.

**Comment by asfaltboy** [comment]
On it. Say, how do you feel about adding a `.python-version` to automate `pyenv local` resolution? Since `tox.ini` now tests against multiple python versions, the contributor might get confused (I'll also add a paragraph about `pyenv`). Otherwise, I'd modify doc to say `tox -e py27` and explain that env must match installed python... I may also add both alternatives if you prefer that.

**Pull request merged**
